### ISSUE TITLE
npm i -g nodemon

### ISSUE THREAD

**Issue by snhasani** [kadamwhite/expresspress#14]
please tell the people first install nodemon package globally, then run command npm start.
maybe someone not installed it before.

**Comment by kadamwhite** [comment]
@snhasani Good catch! I'd actually meant to install nodemon as a dev-dependency, so that `npm start` would work without that step, but I neglected to do so. I appreciate the report, and I'll address it today.

**Comment by snhasani** [comment]
@kadamwhite thank you :+1:

**Comment by kadamwhite** [comment]
Going to leave this open until I get it properly fixed :)
